language: node_js

node_js:
  - 8
  - 10
  - 12
  - 13

notifications:
  email:
    recipients:
      - magic@wizardtales.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/509c88551a18006fe93f
    on_success: change
    on_failure: always
    on_start: never

os:
  - linux

matrix:
  fast_finish: true

cache:
  npm: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export CXX=g++-4.8; export CC=gcc-4.8;

services:
  - mysql

before_script:
  - sudo mysql -e "create database db_migrate_test;"
  - cp test/db.config.ci test/db.config.json
